---
title: "Oligotyping Analysis"
author: "Marian L. Schmidt"
date: "January 19, 2017"
output: html_document
---

```{r load-libraries, echo = FALSE, message = FALSE, include = FALSE}
library(ggplot2)
library(devtools)
library(phyloseq)
library(vegan)
library(tidyr)
library(dplyr)
library(DT)
library(cowplot)
library(wesanderson) # for pretty colors
library(viridis)
library(data.table)
library(stringr)
library(ape)
library(iNEXT) # iNEXT package for alpha diversity measurements 
source("code/Muskegon_functions.R")
source("code/set_colors.R")
```


## Load in Oligotyping Data
```{r load-oligotyping}
##  Read in the Oligotyping Count file 
oligo_count <- read.table("data/oligotyping/MATRIX-COUNT.txt", header = TRUE, row.names = 1) # Read in the oligotyping file making the first row and columns the column and row names
colnames(oligo_count) <- gsub("X", "", colnames(oligo_count)) # Remove the X that R automatically puts in front of the node numbers in the column names
oligo_count <- oligo_count[ , order(names(oligo_count))] # Order the node numbers to match with taxonomy. 

##  Read in the Oligotyping Taxonomy File
raw_oligo_tax <- read.table("data/oligotyping/oligo.taxonomy") # Read in the oligotyping file making the first row and columns the column and row names
cols <- data.frame(str_split_fixed(raw_oligo_tax[,1], "size_", 2)) # Requires stringr package!
colnames(cols) <- c("Oligotype", "Size")
#cols$Size <- as.numeric(cols$Size)
cols$Oligotype <- gsub("\\|.*","",cols$Oligotype)
oligo_tax <- cbind(cols, raw_oligo_tax$V2)
colnames(oligo_tax)[3] <- "Taxonomy"
oligo_tax <- arrange(oligo_tax, Oligotype) # Order the node numbers to match with oligotype count table 
oligo_tax$Size = NULL
row.names(oligo_tax) <- oligo_tax$Oligotype
oligo_tax$Oligotype = NULL


# Separate the taxonomy
tax <- data.frame(str_split_fixed(oligo_tax$Taxonomy, ";", 7)) # Requires stringr package!
tax <- apply(tax, 2, function(y) gsub("\\s*\\([^\\)]+\\)","",as.character(y))) # remove parentheses with everything inside it
colnames(tax) <- c("Kingdom","Phylum","Class","Order","Family","Genus", "Species")
tax <- data.frame(tax)
tax$Species <- gsub(";","",tax$Species) # Remove the final ; in the species column
row.names(tax) <- row.names(oligo_tax) 

################################################
########## ADD THE PROTEOBACTERIA TO THE PHYLA
phy <- tax
Phylum <- as.character(phy$Phylum)
Class <- as.character(phy$Class)

for  (i in 1:length(Phylum)){ 
  if (Phylum[i] == "Proteobacteria"){
    Phylum[i] <- Class[i]
  } 
}

phy$Phylum <- Phylum
t <- tax_table(as.matrix(phy))

################################################

### Create a phyloseq object
oligoCOUNT <- otu_table(oligo_count, taxa_are_rows = TRUE)
oligoTAX <- tax_table(as.matrix(t))
oligo_data <- phyloseq(oligoCOUNT, oligoTAX)

# Sample Names
samp_names <- rownames(otu_table(oligo_data))

# Create metadata info
df <- data.frame(matrix(NA, ncol = 1, nrow = length(samp_names)))
colnames(df) <- c("names")
df$names <- samp_names
```

# Load in Metadata
```{r metadata-load}
# Create metadata info
meta_df <- make_muskegon_metadata(df)

# Create a norep_water_name column
meta_df$norep_water_name <- paste(substr(meta_df$names,1,4),substr(meta_df$names,7,9), sep = "")

# Load in the extra metadata for the Muskegon Lake Project
musk_data <- read.csv("data/metadata/processed_muskegon_metadata.csv", header = TRUE) # Load in the extra metada
musk_data_subset <- select(musk_data, -c(lakesite, limnion, month, year, project, season))
complete_meta_df <- left_join(meta_df, musk_data_subset, by = "norep_water_name")
row.names(complete_meta_df) <- complete_meta_df$names

complete_meta_df$water_name <- paste(substr(complete_meta_df$names,1,5),substr(complete_meta_df$names,7,9), sep = "")
complete_meta_df$norep_filter_name <- paste(substr(complete_meta_df$names,1,4),substr(complete_meta_df$names,6,9), sep = "")
```


## Add metadata to the phyloseq objects to Merge samples
```{r merge_samples}
# Add the metadata to our phyloseq object! 
sample_data(oligo_data) <- complete_meta_df
oligo_data <- prune_taxa(taxa_sums(oligo_data) > 0, oligo_data)

# Merged metadata
merged_complete_meta_df<- 
  select(complete_meta_df, -c(names, replicate, nuc_acid_type, water_name)) %>% 
  distinct() %>%
  arrange(norep_filter_name)


## Add Production data from GVSU AWRI provided by the lab of Bopi Biddanda
bopi_data <- read.csv("data/metadata/production_data.csv") %>%
  dplyr::rename(norep_filter_name = names)  %>% # rename "names" column to "norep_filter_name"
  select(-c(X, limnion, fraction, month, year, season))

## Merge two metadata files together!
df1 <- full_join(merged_complete_meta_df, bopi_data) %>%
  select(-c(Depth, month)) 

# provide row.names to match sample
row.names(df1) <- df1$norep_filter_name

# merge samples for Oligotypes
oligo_merged <- merge_samples(oligo_data, group = "norep_filter_name", fun = "sum")

# Add nice sample information
sample_data(oligo_merged) <- df1


```



